const initialState = {
	window: 'no',
	comments_block: 'hide',
	comments: [],
	active_poll: {'id':0, 'options':[]},
    polls: [],
	sended_polls: 0,
	new_polls_count: 0,
	new_rooms_count: 0,
    tags: [],
	poll_section: 1,
	user: 0,
	voice_sended: 0,
	voices: [],
	voices_count: '',
	rooms: [],
	room_tags: [],
	poll_form_tags: [],
	rooms_form_tags: [],
	room_section: 1,
	room: {author:{name:'',avatar:''},tags:[]},
	answers: [],
	poll_saved: 0,
	room_saved: 0,
	notifications: [],
}

export default initialState