# Generated by Django 3.2.6 on 2023-02-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='webcite',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
