# Generated by Django 3.2.6 on 2023-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_profile_webcite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
